### PR TITLE
Buttons for earlier, later and current departure time

### PR DESCRIPTION
**Pull request by csolem**
Buttons below itinerary suggestions that allows you to choose earlier, later or current departure times.
The times that are subtracted or added are made configurable.

### CODE REVIEW

**Comment by hannesj** [comment]
The logic for showing next and previous departures should be according to the issue [DT-807](https://digitransit.atlassian.net/browse/DT-807)

**Comment by kalon33** [comment]
@hannesj: A bit offtopic: Is it possible for people other than digitransit "core" developers to have an account on atlassian to report issues (and prevent them from reporting something that is planned for later or worked on) or is this reserved to them? 


----- Mail original -----

De: "Hannes Junnila" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Envoyé: Mercredi 6 Avril 2016 13:54:30 
Objet: Re: [HSLdevcom/digitransit-ui] Buttons for earlier, later and current departure time (#477) 



The logic for showing next and previous departures should be according to the issue DT-807

**Comment by samuliheljo** [comment]
Ideally we would like to make our work more transparent by opening Jira more. Unfortunately Jira agile views cannot be shared for anonymous users:
https://jira.atlassian.com/browse/JSW-12623

We are kind of pondering how this transparency should be implemented. We have granted access to some third party developers, so that is "kind of working solution" but it won't scale.

Probably we try to increase roadmap communication through http://digitransit.fi/en

We understand that having issues in GitHub and Jira is confusing for you and not an optimal solution.

**Comment by kalon33** [comment]
Sure this is confusing, especially that I have no access to Jira even if I contribute bug reports and translations... So I don't know what is already reported or has to be. 


----- Mail original -----

De: "Samuli Heljo" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Mercredi 6 Avril 2016 14:19:14 
Objet: Re: [HSLdevcom/digitransit-ui] Buttons for earlier, later and current departure time (#477) 



Ideally we would like to make our work more transparent by opening Jira more. Unfortunately Jira agile views cannot be shared for anonymous users: 
https://jira.atlassian.com/browse/JSW-12623 


We are kind of pondering how this transparency should be implemented. We have granted access to some third party developers, so that is "kind of working solution" but it won't scale. 

Probably we try to increase roadmap communication through http://digitransit.fi/en 


We understand that having issues in GitHub and Jira is confusing for you and not an optimal solution.

**Comment by samuliheljo** [comment]
I'll discuss about this with our Product owner and see what we can do about it.

**Comment by hannesj** [comment]
@kalon33 It seems there has been a permission issue on our JIRA instance since the update to JIRA 7. Now anonymous users are able to view issues, create them and add comments.

The access to the Agile board is still limited by JSW-12623

**Comment by kalon33** [comment]
@hannesj Thanks, indeed that works now :) Should I copy my bug reports/feature requests in Github to JIRA then in order for them to be easily considered? I especially talk about #451 , that impairs my everyday use in Paris.

**Comment by samuliheljo** [comment]
Let's move this conversation over to #451

**Pull request merged**
