### PR TITLE
Remove hardcoded paths

### PR DESCRIPTION
**Pull request by leonardehrenfried**
## Proposed Changes

The application contained a few places where there were hardcoded Finnish URL paths. This PR removes them and replaces them the constants or with function parameters.

Tests were also adjusted.

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

### CODE REVIEW

**Comment by vesameskanen** [comment]
Hi Leonard,

Thanks for the new contribution. I think there is  a slight problem: npm packaged components (digitransit-component, digitransit-search-util) must not depend on digitransit application code (more precisely app/util/path.js).

I do not see any other solution as declaring the required paths as optional new props, which default to old hard-coded values, so that current API will not break. 

Some of the  new path props can perhaps be hash maps where multiple paths are defined. For example:

static defaultProps = {
    prefixMap:  { prefixRoutes: 'linjat', prefixStops: 'pysakit' },
   ...

I hope you get the idea.

**Comment by leonardehrenfried** [comment]
Yes, that sounds reasonable. However, my patch doesn't add a dependency on application code. Am I right in thinking that you would like the method signature to remain the same?

I have question though: the packages I touched aren't react components but plain functions. In order to make them backwards-compatible, I would add an optional `opts` parameter and set default values in the function itself. 

Is this what you imagined?

**Comment by vesameskanen** [comment]
To clarify  further, I'd like to pinpoint one specially problematic line:

https://github.com/HSLdevcom/digitransit-ui/blob/868580e05699a1c2ab7a01630272bf7da792f469/digitransit-component/packages/digitransit-component-autosuggest/src/index.js#L22

The components are already being used in other web applications, and import paths referring outside the code of the npm module itself cannot be used.

Regarding method signature: I think you got my idea correctly. We do not wish to introduce breaking changes without a good reason, so backward compatibility should be maintained whenever possible.

Anyway, if this requirement seems to lead to complicated code and overly deep prop drilling, we should use common sense and change the interface. Please use your own consideration while implementing the changes.

**Comment by leonardehrenfried** [comment]
> https://github.com/HSLdevcom/digitransit-ui/blob/868580e05699a1c2ab7a01630272bf7da792f469/digitransit-component/packages/digitransit-component-autosuggest/src/index.js#L22

Oh yes, you're totally right. I totally overlooked this!

I will fix it and implement your requests.

**Comment by leonardehrenfried** [comment]
I have reworked this PR and it's ready for another review.

**Pull request merged**
