### PR TITLE
Rutebanken load scss from config name

### PR DESCRIPTION
**Pull request by csolem**
- Load sass theme in webpack config based on env variable name.
- Git ignore themes other than hsl and default
- Git ignore config other than hsl, client and default. 
- Git ignore svg-sprite.*.svg other than svg-sprite.hsl.svg and sv-spring.default.svg.

### CODE REVIEW

**Comment by samuliheljo** [comment]
Hi, we'll dig into this tomorrow more closely.

We'll probably need to make slight changes because this approach requires us to define theme in the build phase. That causes us to build two different docker images, which is something that we don't want to do. We try to keep all these params as run options for docker containers.

Anyways, I'm sure we find some solution that works for us both.

I'll continue with this tomorrow...

**Comment by csolem** [comment]
Hi. I see. What about leaving the hsl theme, and just configuring an additional theme? I have updated the pull request.

**Comment by samuliheljo** [comment]
Yep, that was also my initial thought. I'll try how this new version works...

**Comment by hannesj** [comment]
Also see webpack/webpack#370

**Comment by csolem** [comment]
New version that just takes everything in sass/themes. Does not require env variable.

**Comment by hannesj** [comment]
Thanks, looks good to me!

**Pull request merged**
