### PR TITLE
Show departure time as "now" and not 0 minutes

### PR DESCRIPTION
**Pull request by csolem**
* Moving logic from time utils to departure time because of the need for translations
* translations for "now" and "min"
* Using moment for comparing times

### CODE REVIEW

**Comment by samuliheljo** [comment]
Sweet, this feature is good.

Some changes, please:
- Let's use capitalized "now" --> "Now"

**Comment by kalon33** [comment]
How would we deal with languages where "Now" is a particular long word, like French "Maintenant" (or "Imminent")? (Yes, I know, we have long words to say short things) 

----- Mail original -----

De: "Samuli Heljo" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Envoyé: Jeudi 14 Avril 2016 09:27:15 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496) 



Sweet, this feature is good. 

Some changes, please: 

    * Let's use capitalized "now" --> "Now"

**Comment by samuliheljo** [comment]
Hmm.. "Now" is translated value. This solution would allow couple of options:
a) Find some good word which is shorter (maybe not possible?)
b) Use "0 min" as French translation
c) More good ideas?

**Comment by kalon33** [comment]
c) Use an abbreviation of the original word (if that seems good), for example Imm. (but that would need to have a dedicated translation used for this and not shared with other parts of the interface where the full word fits)? 


----- Mail original -----

De: "Samuli Heljo" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 10:22:44 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496) 



Hmm.. "Now" is translated value. This solution would allow couple of options: 
a) Find some good word which is shorter (maybe not possible?) 
b) Use "0 min" as French translation 
c) More good ideas?

**Comment by samuliheljo** [comment]
Additional question: is there different words in French for:
- "Now", as in "Set time as now"
- "Now", as in "Arriving soon"

**Comment by kalon33** [comment]
* "Now", as in "Set time as now" : Maintenant 
    * "Now", as in "Arriving soon" : A l'approche (in this particular transportation context, means that the vehicle is approaching to the stop), Proche (means that the vehicle is near the stop), Imminent (will arrive pretty soon) 

I may miss some of them, but these are all currently used on various french trip planners or transportation networks. 

BTW, we already have the word size problem when setting time of departure in Digitransit, as "Maintenant" is bigger than the button around it. 

----- Mail original -----

De: "Samuli Heljo" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 10:39:41 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496) 



Additional question: is there different words in French for: 

    * "Now", as in "Set time as now" 
    * "Now", as in "Arriving soon"

**Comment by csolem** [comment]
How about using two translations for `now` in this pull request; `now-short`, and `now`? For languages that have short words for `now`, translations could be the same. But for French, you could use, as mentioned, an abbreviation for `now-short`. Supporting "set time as now", "arriving soon", "near the stop" and so on seems to be something we should discuss further.

**Comment by samuliheljo** [comment]
I think we need one translation for "Now" as a button in bottom. Maybe id: 'now'
screen shot 2016-04-14 at 12 39 58

Then a second translation "Now" as a "arriving soon". Maybe is : 'arriving-soon'.

I would probably set then 
FR: 
- 'arriving-soon': 'Imm.', 
- 'now':'Maintenant'

EN:
- 'arriving-soon': 'Now', 
- 'now':'Now'
 
would that work?

**Comment by kalon33** [comment]
That doesn't seem a bad idea as a temporary fix until discussing further, sure. 


----- Mail original -----

De: "csolem" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 11:38:34 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496) 



How about using two translations for now in this pull request; now-short , and now ? For languages that have short words for now , translations could be the same. But for French, you could use, as mentioned, an abbreviation for now-short . Supporting "set time as now", "arriving soon", "near the stop" and so on seems to be something we should discuss further.

**Comment by kalon33** [comment]
That's not a problem anymore for the buttons it seems as the only remaining one is the bottom button (which is pretty large) where it fits. It used to be when we had the "now" button near the departure/arrival time setting (at the top). Still, the "today" french equivalent "Aujourd'hui" is too big for it. 


----- Mail original -----

De: "Samuli Heljo" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 11:43:43 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496) 



I think we need one translation for "Now" as a button in bottom. Maybe id: 'now' 



Then a second translation "Now" as a "arriving soon". Maybe is : 'arriving-soon'. 

I would probably set then 
FR: 

    * 'arriving-soon': 'Imm.', 
    * 'now':'Maintenant' 


EN: 

    * 'arriving-soon': 'Now', 
    * 'now':'Now' 


would that work?

**Comment by samuliheljo** [comment]
Just as a heads up, summary page top will soon (in one month) look like this

screen shot 2016-04-14 at 11 44 56

**Comment by samuliheljo** [comment]
So "Lähtee tänään klo. 14:12" will work as time edit.. (In case Finnish is not yet in your vocabulary)

**Comment by samuliheljo** [comment]
So @csolem, two translations it is.

**Comment by csolem** [comment]
french arriving soon

**Comment by kalon33** [comment]
That would take a dot after Imm "Imm." as it's an abbreviation but that's clearly better looking now :) 

Thanks! 


----- Mail original -----

De: "csolem" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 12:59:04 
Objet: Re: [HSLdevcom/digitransit-ui] Show departure time as "now" and not 0 minutes (#496)

**Comment by samuliheljo** [comment]
Looks good. Thanks everyone!

**Pull request merged**
