### PR TITLE
Precompress and optimize static files during build and serve them to browsers

### PR DESCRIPTION
**Pull request by gmokki**
The PR is done - it:
- [x] follows the style and naming rules (passes `npm run lint`)
- [x] doesn't break anything (passes `npm run test-local` and `npm run test-browserstack`)
- [x] any changed files are transformed to ES6

Changes:
- create precompressed variants of js, css, svg files: gz using zopfli and br using brotli

Currently using forked versions of expressjs/send/negotiator while waiting for the PRs to go through:
- https://github.com/jshttp/negotiator/pull/49
- https://github.com/pillarjs/send/pull/108

### CODE REVIEW

**Comment by hannesj** [comment]
Is there some reason not to use a ready-made plugin like https://webpack.js.org/plugins/compression-webpack-plugin/ ?

**Comment by gmokki** [comment]
Only familiarity of basic unix tools.

I can try to use webpack plugins:
- https://webpack.js.org/plugins/compression-webpack-plugin/ for zopfli compression
- https://github.com/ngsru/brotli-webpack-plugin for the brotli compression
- https://www.npmjs.com/package/imagemin-webpack-plugin for pngquant, svgo
- and somehow figure out how to add https://github.com/imagemin/imagemin-zopfli to the imagemin-webpack-plugin

Or maybe I will just leave the image optimizations out of this PR...

**Comment by hannesj** [comment]
I think the imagemin-zopfli plugin can be added using [this](https://www.npmjs.com/package/imagemin-webpack-plugin#optionsplugins)

**Comment by hannesj** [comment]
Also check https://github.com/HSLdevcom/digitransit-ui/pull/1031 where we have included the svgs to be bundled using webpack.

**Comment by hannesj** [comment]
Implemented the serving using a different express middleware, so we can use the vanilla express version.

See https://github.com/HSLdevcom/digitransit-ui/pull/1074/commits/cc2c7f0579cb46672240929ccd6da02889f007f1

**Pull request closed without merging**
