### PR TITLE
Configurable card header description for stop place card

### PR DESCRIPTION
**Pull request by csolem**
Making it possible to not show the stop card header description in stop cards.

### CODE REVIEW

**Comment by samuliheljo** [comment]
Could you elaborate little bit, why not show stop info?

**Comment by csolem** [comment]
The reasons for this are

1. Our values for `@props.stop.code` is not always a public code that is interesting for the user of the application
2. Our current gtfs data is somewhat not yet consistent enough
3. If one of the fields are empty, we end up with trailing `//`

**Comment by kalon33** [comment]
To add my two cents: In GTFS data I use in France, stops numbers or ids are not known from the public (only from people who have to deal with data). Only stop names are, so in this situation it would be better to hide them.

**Comment by csolem** [comment]
Maybe we could make each one of them (desc/code/distance) configurable, and do something about the slashes?

**Comment by kalon33** [comment]
That seems great to me, but I'm not the one who decides ;)

**Comment by samuliheljo** [comment]
Based on discussion above, I would make all 3 configurable. Once those modifications are here, I shall merge.

**Comment by samuliheljo** [comment]
Thanks!

**Pull request merged**
