### PR TITLE
Implemented colors to match the GTFS colors

### PR DESCRIPTION
**Pull request by AlexLoyko**
Finally, after a series of struggles with making it look nice and neat, please review my latest and (hopefully) last version of #1529 and #1513, which fixes both the leg markers' colors and hidden stops colors bugs.

Solves #537.

### CODE REVIEW

**Comment by laidig** [comment]
We'd appreciate a look at this if there is a chance of a merge.

**Comment by kalon33** [comment]
@laidig @alexloyko just activated disruptions info on my digitransit instance (with this PR merged), and route colors are not used for it. Could you fix this please? Thanks :)

**Comment by kalon33** [comment]
@AlexLoyko Did you saw my remark about missing line colors in disruptions menu?

**Comment by laidig** [comment]
@kalon33 we currently don't have a working disruption source so we can't test out that functionality. 

@hannesj @tuukka  If someone can give this a look over, we would greatly appreciate it before falling too far out of sync again.

**Comment by kalon33** [comment]
@laidig @AlexLoyko If you provide some code, I will be happy to test it on my setup (https://transit.paris), where you can see the current look of it (disruptions screen on home page, and https://transit.paris/linjat/3:100110004:4/hairiot for example):

disruptions_screen

disruptions_screen_line

**Comment by hannesj** [comment]
@AlexLoyko @laidig Sorry, I've been working on another project for past couple of weeks. I will try to get a look at this today or latest early next week. 

PS. You don't need to create a new PR if you want to make some changes. You can just push changes into the same branch and the PR is updated accordingly.

**Comment by AlexLoyko** [comment]
@kalon33 Please test routeColors for disruptions. Let me know if it works:)

**Comment by kalon33** [comment]
@AlexLoyko that's fixed for the situation in the 2nd picture, but not the first one, when, from the home page, you click on the danger sign in the upper right of the page (first screenshot), thanks :)

**Comment by laidig** [comment]
KIITOS!

**Pull request merged**
