### PR TITLE
Add RouteSchedule view.

### PR DESCRIPTION
**Pull request by apkoponen**
Here's an initial implementation for the RouteSchedule view for you to take a look. I did not have a proper visual design (PSD etc., only the raster in InVision) for the view so the visual look will need some work. In addition, the select field looked like you had in mind to use some JS library for enhancement (such as chosen.js), so I did not spend time styling it so that all selects with the new style will have an unified look.

The pull request does not yet include tests or contributions to styleguide, as the style is not yet testable.

### CODE REVIEW

**Comment by samuliheljo** [comment]
Rock on! For starters, I'll attach PSD file here.

[HSL_Reittiopas_ios_line_timetable.psd.zip](https://github.com/HSLdevcom/digitransit-ui/files/295494/HSL_Reittiopas_ios_line_timetable.psd.zip)

**Comment by apkoponen** [comment]
Did you have plans for using some select library or will I just style the selects according to the design?

**Comment by hannesj** [comment]
You could check out if it is possible to use [SelectField](http://www.material-ui.com/#/components/select-field) from material-ui, which is already included in the project.

**Comment by hannesj** [comment]
Also, the data should be available in the GraphQL endpoint after HSLdevcom/OpenTripPlanner#63 gets merged.

**Comment by samuliheljo** [comment]
That is now merged. Server side should now have needed api available in
https://dev-api.digitransit.fi (used by default when developing on local
machine)


On Thursday, 2 June 2016, Hannes Junnila <notifications@github.com> wrote:

> Also, the data should be available in the GraphQL endpoint after
> HSLdevcom/OpenTripPlanner#63
> <https://github.com/HSLdevcom/OpenTripPlanner/pull/63> gets merged.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HSLdevcom/digitransit-ui/pull/670#issuecomment-223311719>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPQWtzuSlnVzmXbMrWK73f-FgjGnPE_ks5qHuqjgaJpZM4IsFLi>
> .
>


-- 

--
Samuli Heljo
+358 50 3537299

**Comment by samuliheljo** [comment]
so to query timetable for date, this works in
https://dev-api.digitransit.fi/routing/v1/routers/hsl/index/graphql

````
{
  pattern(id: "HSL:1001:0:01") {
    stops {name}
    tripsForDate(serviceDay: "20160606") {
      stoptimes {
        scheduledDeparture
      }
    }
  }
}
```

**Comment by samuliheljo** [comment]
this is now available in api.digitransit.fi

http://dev.hsl.fi/graphql/console/?query=%7B%0A%20%20pattern(id%3A%20%22HSL%3A1001%3A0%3A01%22)%20%7B%0A%20%20%20%20stops%20%7Bname%7D%0A%20%20%20%20tripsForDate(serviceDay%3A%20%2220160606%22)%20%7B%0A%20%20%20%20%20%20stoptimes%20%7B%0A%20%20%20%20%20%20%20%20scheduledDeparture%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

**Comment by apkoponen** [comment]
I updated the solution. It is still lacking

General questions
- Do you have any examples on how the svg icons could be used in CSS? Currently the arrow in the dropdown is just placed with position:absolute which is not ideal.
- Which tests should I use as an example for creating my tests?

TODOs I would need help with:
- How do we distinguish between Route change and just the date change with Relay?
- How do we get the current date when defining the Relay fragment?

**Comment by apkoponen** [comment]
The TODOs should be done now.

**Comment by hannesj** [comment]
Hi,

Sorry for taking so long to respond. We really appreciate the work you have done.

As for the questions you have:

> Do you have any examples on how the svg icons could be used in CSS? Currently the arrow in the dropdown is just placed with position:absolute which is not ideal.

Sorry, I don't think we have found any proper way to do this at the moment. I think your solution works good enough until we have some proper way of doing this. Do you have suggestions?

> Which tests should I use as an example for creating my tests?

You could add a static description to your components and add the non-Container components to our style guide page. You can take a look at how the components in the `app/component/documentation`-folder are being used. You can also add example timetable data. After those have been added, visual tests for the components should be added. This can be done by us if you don't have a BrowserStack account. 

> Was there a design for the case, when no trips exist for the given date? This is the case in e.g. /linjat/HSL:1062:0:01 for saturday and sunday.

There should only be the stop selectors and below them a text visible that says something like `No timetable available for the selected date`

> How do we distinguish between Route change and just the date change with Relay?
> How do we get the current date when defining the Relay fragment?

For the getting the current date I would suggest wrapping the relay container in a `connectToStores`-wrapper which gives the relay-component the current date in a prop that has the same name as the variable, i.e. `serviceDay`. That way the query is updated by relay always when the prop is updated.

I can make a sample of this in a new branch in our repo if that is ok with yo.u

Also a couple of point from a quick review:

- The header with the date and stop selection should be sticky and only the timetable list be scrollable. The route header will shrink in the new designs so it should still be usable.
- We try to minimize the amount of state and discourage saving things in the state that are easily recalculated during render in order to only have a single source of truth. Thus state.stops and state.trips should probably be recalculated every time in render, if there is no convincing points for doing this.

We are willing to help if there is any questions you have and we are preparing to merge this during the beginning of next week in order to have it included in our beta launch on the 15th. We are having a launch presentation during the [InformNorden](http://nordicpublictransport.com/) conference. Would it be ok to name you as the newest of the contributors during the presentation when describe the community that is starting to form around our project?

**Comment by hannesj** [comment]
I implemnted the date initialization logic from the store as well as removed the redundant information kept in the state in https://github.com/HSLdevcom/digitransit-ui/commit/e91e131a432d54acdea7ec5d72bfdaeb41819c8a . Could you check if this is ok with you?

**Comment by apkoponen** [comment]
> Sorry, I don't think we have found any proper way to do this at the moment. I think your solution works good enough until we have some proper way of doing this. Do you have suggestions?

I don't know how easy it would be to make CSS classes for the icons (svg's as bg-images), but with them it should be quite easy.

Thanks for the initilization logic & state simplification, I merged them to my branch. I was already getting exited about refactoring the state last night in bed, but you got there first. :) I'll check out the documentation and make the elements testable. I currently don't have my own BrowserStack account.  

However, I don't know how much time I have today and tomorrow to finishing the view, so feel free to do whatever you must to include it in the beta.

Also, I'm not sure how much time I can contribute for the project (as you've probably noticed, my progress has been quite slow), but you're welcome to add my name to the list, if you wish. The more the merrier!

**Comment by apkoponen** [comment]
I think everything should now be in place for you to review the code & make BrowserStack tests.

**Comment by hannesj** [comment]
Thanks!

Sorry for too eagerly removing the `componentWillReceiveProps` :sweat: The descriptions look good, I'll integrate them to the tests tomorrow and hopefully get this merged.

No problem with not being able to contribute much, we just would like to name you as the author of our most recent feature. In the future, if there is something you feel something else is missing, we are more than welcoming for additional PRs ;)

**Comment by hannesj** [comment]
@apkoponen It's now merged. Thanks for the help, it is appreciated!

**Pull request merged**
