### PR TITLE
Development feature flag for navigation

### PR DESCRIPTION
**Pull request by vesameskanen**
Navigation shows up only in local server and in development environment

### CODE REVIEW

**Comment by partisaani** [comment]
I'd like to suggest we nest feature flagged properties under a set feature flag object so that their nature is crystal clear.

**Comment by vesameskanen** [comment]
please push a suggested change to this branch

**Comment by vesameskanen** [comment]
Actually, large part of configuration consists of 'feature flags'. A value will trigger a feature which appears in the UI.

**Comment by partisaani** [comment]
That is very much true, and my wording was not as well thought initially. What I meant was to have i.e.
```javascript
  experimental: {
    navigation: process.env.RUN_ENV === 'development' || process.env.NODE_ENV !== 'production',
  },
```
which would help spotting these in development features among the other properties that are used to flag features on and off between service providers.

If you feel like it's just an unnecessary overhead, the suggestion may be disregarded - the change itself looks good, and I am for merging it to `v3`

**Review by partisaani — APPROVED** [review]
LGTM

**Pull request merged**
