### PR TITLE
NRP-1132 Use 2x tiles if retina tiles configured OR L.Browser.retina

### PR DESCRIPTION
**Pull request by Eightyplus**
Use 2x tiles if retina tiles configured OR L.Browser.retina.

### CODE REVIEW

**Comment by hannesj** [comment]
Is there some reason for this? The config option is there to indicate that the map server supports both regular and retina tiles, as the not all providers supply both.

**Comment by Eightyplus** [comment]
The default configuration for useRetinaTiles is true, so right now the browser decides whether to display larger map tiles. We think the map looks way better by forcing 2x, and would like to share this with you.

**Comment by hannesj** [comment]
Sorry that I haven't replied. I just don't really understand the point of the option, as the tiles supplied should be of the same quality as long as the ppi matches. 

I checked your site, and it seems you are using 256px tiles, which means you should be using the following options in your config instead of the supplied:

`
map.tileSize: 256,
map.zoomOffset: 0
`

**Comment by Eightyplus** [comment]
Thanks this actually solves the resolution problem and not the pull request.

**Pull request closed without merging**
