### PR TITLE
Implemented line colors to match the GTFS colors

### PR DESCRIPTION
**Pull request by AlexLoyko**
In this commit I have implemented the feature described in #537. 
A few comments: shouldn't this line https://github.com/HSLdevcom/digitransit-ui/blob/master/app/component/TransitLeg.js#L98 be a RouteNumberContainer instead?
Is there enough testing or should I work on tests myself?"

### CODE REVIEW

**Comment by laidig** [comment]
A hint from the docs:
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Installation.md#configure-git-hooks

`npm run test-local` will run the tests locally.

**Comment by kalon33** [comment]
@AlexLoyko Would it also be possible to change line number color and the color of the shape containing that number on the map to comply GTFS data? Thanks :)

**Comment by AlexLoyko** [comment]
It does it already I assume.

**Comment by AlexLoyko** [comment]
Just can't push it yet, get the BroserStack credentials missing. Any idea how to fix this quickly?)
Thanks:)

**Comment by kalon33** [comment]
@AlexLoyko Apparently not, I just tested it locally:
screenshot_2017-04-06-21-47-39

As you can see, the route has the proper color on the map, but the "tag" with the line number on the map doesn't have the proper color (around the tag, and the line number text).

**Comment by AlexLoyko** [comment]
Sure. I'll fix it ASAP.

**Pull request closed without merging**
