### PR TITLE
Only use M for subway if shortName not available

### PR DESCRIPTION
**Pull request by csolem**
The PR is done - it:

- [ ] follows the style and naming rules (passes `npm run lint`)
- [ ] doesn't break anything (passes `npm run test-local` and `npm run test-browserstack`)
- [ ] design is as expected. NOTE! visuals are compared using HSL theme (`CONFIG=hsl npm run dev`).
-- If no design changes: `BS_USERNAME=user BS_ACCESS_KEY=key npm run test-visual` passes
-- If design changes: `BS_USERNAME=user BS_ACCESS_KEY=key npm run test-visual-update` to generate new images
- [ ] any changed files are transformed to ES6
- [ ] all changed components

  * [ ] have examples
  * [ ] have unit tests
  * [ ] are included in the style guide
  * [ ] are included in the visual tests (added to gemini tests)

If this PR fixes a bug, it includes a new test that catches the bug to prevent regressions.

### CODE REVIEW

**Comment by hannesj** [comment]
Hi, you can actually remove the hard coded `M` altogether. This is a data issue for us and should not require any extra configuration

**Comment by tuukka** [comment]
@hannesj Will you fix the data?

**Comment by hannesj** [comment]
This seems to be fixed in JORE for the new IDs 31M1 and 31M2.
13.6.2016 11.05 ap. "Tuukka Hastrup" <notifications@github.com> kirjoitti:

**Comment by tuukka** [comment]
@hannesj It'll take half a year or so before those are in operation. I think we want to merge this earlier. And in the latest GTFS data, they are still broken:
```
31M1,HSL,,Helsinki-Siuntio,,1,https://www.vr.fi/cs/vr/fi/paakaupunkiseudun_lahiliikenne
31M1B,HSL,B,Helsinki-Siuntio,,1,https://www.vr.fi/cs/vr/fi/paakaupunkiseudun_lahiliikenne
```

**Comment by hannesj** [comment]
@tuukka This is still a data issue that should be fixed upstream and not special cased by us, if we want to have a generic solution. Also there is only one subway, and the icon still reflects that.

**Comment by tuukka** [comment]
@hannesj If you want to change the design to remove the M, I'm personally fine with it as long as it doesn't end up saying "null" or "undefined" ;-) By the way, I notice we call this function only in SummaryRow while we use shortName directly a lot.

**Comment by hannesj** [comment]
Yes, after removing the hardcoded value, it looks like this:

screen shot 2016-06-13 at 14 36 06
screen shot 2016-06-13 at 14 36 18
screen shot 2016-06-13 at 14 36 41

The last picture is unchanged from the [current one](https://beta.reittiopas.fi/linjat/HSL:1300V:0:02), only hte summary page is affected.

**Comment by hannesj** [comment]
@tuukka I'll merge this as is. We can remove the config after the shortName is included on the GTFS bundle.

**Comment by tuukka** [comment]
:+1: Thanks @hannesj and @csolem!

**Pull request merged**
