### PR TITLE
Add trip headsign in itinerary details

### PR DESCRIPTION
**Pull request by kalon33**
Here is an implementation of trip headsign display next to bus number, according comments in #451 

Screenshot of what it gives:
screenshot_2016-04-11-22-25-48

Thanks to @tuukka , @samuliheljo , @hannesj (if it's good for you, https://digitransit.atlassian.net/browse/DT-839 is good to be closed :) ), and @Macroz for their help and comments.

### CODE REVIEW

**Comment by kalon33** [comment]
@hannesj could you have a look at this?

Simple curiosity, how are pull request handled and reviewed by the team?

Thanks :)

**Comment by hannesj** [comment]
@kalon33 If you could look at the issue pointed by @Macroz and move the text from TransitLeg down to the individual types of legs, e.g. BusLeg, TramLeg, as we probably don't want to include the destination e.g. for Airplanes, where usually the headsign is the same as the destination for the leg.

**Comment by kalon33** [comment]
@hannesj Ok I will take some time to look at it. I didn't properly understood first (when @Macroz commented it) why it would be a problem until you raised Airplanes problem, as in France we currently have no GTFS Airplanes data to integrate to OTP at all, and thought it would be the same everywhere. 


----- Mail original -----

De: "Hannes Junnila" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Jeudi 14 Avril 2016 09:59:05 
Objet: Re: [HSLdevcom/digitransit-ui] Add trip headsign in itinerary details (#494) 



@kalon33 If you could look at the issue pointed by @Macroz and move the text from TransitLeg down to the individual types of legs, e.g. BusLeg, TramLeg, as we probably don't want to include the destination e.g. for Airplanes, where usually the headsign is the same as the destination for the leg.

**Comment by samuliheljo** [comment]
So here is how our process works:
Our project is funded By Helsinki Region Transport and Finnish Transport Agency and we have limited resources allocated to the project. Main driving force for changes are needs of these two organisations and they are ultimately controlling how our 8 person team uses its time.

We work using Scrum and do it in 2week sprints. All our changes are done using pull request model and we have agreed that "someone else from the development team does the review". Same model applies for community based pull request, "someone from development team" does the review when time is available.

As probably all IT related projects, we have more to do than we have time for. That's why some pull requests, especially "non critical", will take more time to get merged. "Critical" is of course subjective.

I want to highlight that we value community based pull request. We have many stakeholders that we try to keep happy and therefore we try to find right balance for "community support" and "project needs". Ideally these two would be same thing.

We are learning this as we go, therefore feedback like yours is very valuable.

To give you more insight, Digitransit-ui is used in Helsinki and also as Finnish national transport. In addition, Digitransit-ui is used in Norway. We have different needs depending on the installation. E.g. Airplane support has been very critical for Norway, as it's there only viable way to get to some places up north (to my understanding).

Hope this clears things for you!

**Comment by kalon33** [comment]
@samuliheljo Sure it does :) It's good to know how things are working, with better understanding everybody is more tolerant. Thanks !

For the PR, I will try to take some time to do this today or tomorrow evening after work.

**Comment by kalon33** [comment]
@hannesj @samuliheljo As planned, I found some time to look at it this evening. Is that now what you wanted?

**Comment by Macroz** [comment]
We are now merging a bunch of our PRs at the end of sprint. So I'll take a look at this on Monday and do the necessary merges if it looks good.

**Comment by kalon33** [comment]
@Macroz I fixed the merge under latest upstream changes, and took some time to add and fix some french translations. That should make your Monday review easier :)

**Comment by kalon33** [comment]
Snap CI failed but it seems due to network connectivity problem in their environment, it builds properly locally.

**Comment by kalon33** [comment]
@hannesj @samuliheljo @Macroz I think the PR should be good to be merged now (working, rebased on master so no conflicts with it, all checks OK and translations updated/fixed in app context as an extra) :)

**Comment by samuliheljo** [comment]
Ok thanks, i'll try to catch up on pending pull requests today

On Tuesday, 19 April 2016, Nicolas Derive <notifications@github.com> wrote:

> @hannesj <https://github.com/hannesj> @samuliheljo
> <https://github.com/samuliheljo> @Macroz <https://github.com/Macroz> I
> think the PR should be good to be merged now (working, rebased on master so
> no conflicts with it, all checks OK and translations updated/fixed in app
> context as an extra) :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HSLdevcom/digitransit-ui/pull/494#issuecomment-211920963>
>


-- 

--
Samuli Heljo
+358 50 3537299

**Comment by samuliheljo** [comment]
Looks good! Thanks!

**Pull request merged**
