### PR TITLE
Url endpoints

### PR DESCRIPTION
**Pull request by meromisi**
We have forked the repo and wanted to translate the url endpoints to German but it was hard coded in many places through the project, so we replaced them with variables.

Please check out, if it works for You too.

### CODE REVIEW

**Comment by BodoMinea** [comment]
I have tested this on my installation and it seems to work perfectly. 

However, checking with grep, it seems that some files still have hardcoded strings in it. Maybe those are tests or something.

```app/component/TopLevel.js:      case 'pysakit':
test/unit/test-data/dt2887.js:  activeTab: 'pysakit',
test/unit/test-data/dt2887b.js:  activeTab: 'pysakit',
test/unit/component/RoutePatternSelect.test.js:      activeTab: 'pysakit',
test/unit/component/RoutePage.test.js:        pathname: '/linjat/HSL:1063/pysakit/HSL:1063:0:01',
test/unit/component/RoutePage.test.js:        pathname: '/linjat/HSL:1063/pysakit/HSL:1063:0:01',
test/unit/component/RoutePage.test.js:        pathname: '/linjat/HSL:1063/pysakit/HSL:1063:0:01',
test/unit/component/RouteAlertsRow.test.js:      '/linjat/HSL:2097N/pysakit/HSL:2097N:0:01',```

**Comment by meromisi** [comment]
You are right! I replaced them in tests too (where it was neccessary). I checked it and now the project only cointains these words where it is neccessary like in translate.js, comment sections, headers and paragraphs. 
Could you take another look at the modifications? 
Thank you.

**Comment by vesameskanen** [comment]
Thanks! Lint and flow tests error should be fixed. Visual tests won't pass for external pull requests.

**Comment by BodoMinea** [comment]
Lint errors are easily fixable, I also had to work that out on my PRs. I encourage you @meromisi to just use the *prettier* package which is already included for these checks - https://prettier.io/ 

It's straightforward. Just run ```yarn prettier --write src/blah.js``` or configure a task to run before you commit changes and prettify all sources. This way there will be no more test fails.

The flow tests seem to fail on the apparition of ```import { PREFIX_ITINERARY_SUMMARY } from '../../../../app/util/path';``` and with that I have no idea.

**Comment by leonardehrenfried** [comment]
`citybike.js` mixes `import` and `require`. is this perhaps a problem for flow?

**Comment by vesameskanen** [comment]
I will fix the flow test problems and merge the pull request. Thank you for the contribution!

**Pull request merged**
