### PR TITLE
## Proposed Changes

### PR DESCRIPTION
**Pull request by obb12**
-Share button for android
## Tests
 wip

### CODE REVIEW

**Comment by obb12** [comment]
Do you need test to see if navigator.share is available?

**Comment by obb12** [comment]
Pull-request updated, HEAD is now e0d6e14c174c70e670a71b73c2a9ffacfca073da

**Comment by obb12** [comment]
BS_ACCESS_KEY not set, failing build on purpose

**Comment by vesameskanen** [comment]
Thanks for the contribution! We will consider in the near future if the pull request can be merged as it is now, or do we perhaps need to make this a configurable option.

**Comment by vesameskanen** [comment]
Hi! The share button idea was discussed thoroughly in a design session. Unfortunately we cannot use the PR as it is now. Namely, placing the share button into the context of a particular itinerary suggests that use of the shared url would somehow produce a similar route search result. Unfortunately this is not the case, because of constantly changing realtime predictions and user's own preferences. We do have plans to implement a feature for saving the actual static itinerary description, but that is not implemented yet.

Anyway, thank you for bringing up the interesting topic for discussion! Future will show how it evolves.

**Pull request closed without merging**
