### PR TITLE
Feature arrivals

### PR DESCRIPTION
**Pull request by apkoponen**
This is done based on: https://digitransit.atlassian.net/browse/DT-1117

However, it was unclear if other changes than the "Saapuu / Päätepysäkki" information was supposed to be added. The design in the pictures has at least 3 additional changes to current:
- X for closing the pop-up.
- Route number style
- "Näytä lisää" instead of "Reititä täältä". 

Should these be included to this PR?

Otherwise:

- [X] follows the style and naming rules (passes `npm run lint`)
+ NOTE: TileLayerContainer.js makes the test not to pass, not this pull request.

- [] doesn't break anything (passes `npm run test-local` and `npm run test-browserstack`)
+ NOTE: npm run test-local does not seem to work on my Ubuntu, I don't have a BS account. test-local message:
  1) Frontpage "before all" hook:
Connection refused! Is selenium server started?

- [/] design is as expected. NOTE! visuals are compared using HSL theme (`CONFIG=hsl npm run dev`).
+See above

- [X] any changed files are transformed to ES6
- [/] all changed components
  * [X] have examples
  * [ ] have unit tests
  * [X] are included in the style guide
  * [ ] are included in the visual tests (added to gemini tests)

### CODE REVIEW

**Comment by hukka** [comment]
The other design differences are unrelated. I'll review this and add new visuals

**Comment by hukka** [comment]
Is there a reason why example data was changed? That affects quite many of the visual tests, and the departure data seems to be missing relevant properties.

**Comment by apkoponen** [comment]
Oh, sorry. I'll review the changes to the departure data. I changed it in because some fields were added to the query.

**Comment by apkoponen** [comment]
I reverted the changes in the exampleData and only left the added lines.

**Pull request merged**
