### PR TITLE
Use full height when showing nearby/favourites and add exit cross 

### PR DESCRIPTION
**Pull request by csolem**
* Add heading and exit cross on nearby routes panel and favourites panel
* Use full height for panels for nearby routes and favourites
* Move panel for nearby routes to a separate component

### CODE REVIEW

**Comment by samuliheljo** [comment]
Yes, you should keep on working with this :+1: 

Some more detailed designs for you:
hsl_reittiopas_ios_etusivu_lahellasi_02_720
hsl_reittiopas_ios_etusivu_suosikit_02_720

So we added that "X" to close tab also.

I'll check that "front page loads twice" problem...

**Comment by csolem** [comment]
Maybe it's better to store the state of the front page panel in a store, similar to the feedback-store?

**Comment by samuliheljo** [comment]
I havent't had time yet to check that state part. Couple quick insights:
- Back button should close tab as it does now in master version. This is now handled with browser state.
- My initial feel is that removing when tab is opened will not produce any performance improvements and it even might make things slower (it takes time to put it back once tab closes)

Anyways, plan remains the same; let's make that tab as designed in above images. And as you were interested in making tabs take less space, put that as configuration option.

**Comment by samuliheljo** [comment]
You should check how location.state is used here:
https://github.com/HSLdevcom/digitransit-ui/blob/master/app/component/front-page/front-page-panel.cjsx#L52

**Comment by samuliheljo** [comment]
So to sum it up, you have basically two options:
a) wait a bit and let us check whether this "do not render map when x" is actully good way to proceed
b) try to do something for state.

I think that it could be better to go with a) as work with b) might not be needed in the end.

**Comment by csolem** [comment]
I have the same opinion as you. To remove the map and rerender it will probably not gain performance. So I will remove this logic for now.

**Comment by csolem** [comment]
Also, I think the X will do fine for us as well. Because of the X, we can also have full height for panels. Because the original thought was that it should be easy to close favourites/nearby routes. Which means less configuration.

**Comment by csolem** [comment]
Can you please have another look at this now, Samuli?

**Comment by samuliheljo** [comment]
Brilliant! Looks good, Merging.

Extra points for panel refactoring :)

**Pull request merged**
