### PR TITLE
Dt 920 show first vehicle

### PR DESCRIPTION
**Pull request by Macroz**
Implements [DT-920](https://digitransit.atlassian.net/browse/DT-920)

Should test with mobiles and various route combinations.

### CODE REVIEW

**Comment by samuliheljo** [comment]
Overflow:

<img width="139" alt="screen shot 2016-05-10 at 12 18 13" src="https://cloud.githubusercontent.com/assets/1298522/15141588/6e084222-16a9-11e6-83e9-7de033268c07.png

**Comment by samuliheljo** [comment]
screen shot 2016-05-10 at 12 18 13

**Comment by samuliheljo** [comment]
Why is it not showing "first itinerary" but in some case e.g. second?

**Comment by Macroz** [comment]
I'm going over the different mobiles to fit the text.

First itinerary is not shown because we take the first (i.e. "best") route from OTP. In the summary screen we show three "best" routes in the order of departure time (i.e. not in the "best first" order). So the route will be one of the three but not necessarily the first.

**Pull request merged**
